#!/usr/bin/env python3
"""Generate start.sh from start1660.sh template + LauncherConfig."""

from __future__ import annotations

import re
import stat
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from .presets import LauncherConfig


def project_root_from(here: Optional[Path] = None) -> Path:
    if here is None:
        here = Path(__file__).resolve()
    # tools/hybrid_autotune/generate.py -> repo root
    return here.parent.parent.parent


def load_template(project_root: Path) -> str:
    for name in ("start1660.sh", "start1080.sh"):
        p = project_root / name
        if p.is_file():
            return p.read_text(encoding="utf-8")
    raise FileNotFoundError("neither start1660.sh nor start1080.sh found as template base")


def _replace_assignment(text: str, key: str, value: str) -> str:
    """Replace KEY="..." assignment; preserve trailing comment if present."""
    # Match: KEY="..." optional comment
    pat = re.compile(
        rf'^({re.escape(key)})="[^"]*"(.*)$',
        re.MULTILINE,
    )

    def repl(m: re.Match[str]) -> str:
        rest = m.group(2)
        # keep comment part after value
        return f'{m.group(1)}="{value}"{rest}'

    new, n = pat.subn(repl, text, count=1)
    if n == 0:
        # try insert before end of editable config
        marker = "# End of editable configuration"
        if marker in text:
            insert = f'{key}="{value}"  # added by hybrid_autotune\n'
            text = text.replace(marker, insert + "\n" + marker, 1)
            return text
        return text
    return new


def apply_config(template: str, cfg: LauncherConfig) -> str:
    text = template
    for key, value in cfg.values.items():
        text = _replace_assignment(text, key, value)

    # Die / CLI messages should say start.sh for generated launcher
    text = text.replace("start1660.sh:", "start.sh:")
    text = text.replace("start1080.sh:", "start.sh:")
    text = re.sub(
        r'die "Keine Kommandozeilenparameter: Einstellungen oben in start[0-9]*\.sh[^"]*"',
        'die "Keine Kommandozeilenparameter: Einstellungen oben in start.sh aendern."',
        text,
    )
    text = text.replace("./start1660.sh", "./start.sh")
    text = text.replace("./start1080.sh", "./start.sh")

    # Header
    notes = cfg.meta.get("notes", [])
    note_lines = "\n".join(f"#   {n}" for n in notes)
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    header = f"""#!/usr/bin/env bash
#
# llama-wackMall-hybrid auto-generated launcher (start.sh)
#
# Generated by tools/hybrid_autotune at {ts}
# Edit this block or re-run: python3 tools/hybrid_autotune/autotune.py
# Fixed references: start1660.sh (GTX 1660 Ti), start1080.sh (GTX 1080)
#
{note_lines}
#
"""
    # strip original shebang+leading comments until set -Eeuo
    m = re.search(r"^set -Eeuo pipefail", text, re.MULTILINE)
    if m:
        text = header + text[m.start() :]
    return text


def write_start_sh(
    cfg: LauncherConfig,
    project_root: Optional[Path] = None,
    out_path: Optional[Path] = None,
    dry_run: bool = False,
) -> Path:
    project_root = project_root or project_root_from()
    out_path = out_path or (project_root / "start.sh")
    template = load_template(project_root)
    body = apply_config(template, cfg)

    if dry_run:
        print(body[:2000])
        print(f"\n... [{len(body)} bytes total, dry-run not written]")
        return out_path

    tmp = out_path.with_suffix(out_path.suffix + ".tmp")
    tmp.write_text(body, encoding="utf-8")
    tmp.chmod(tmp.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    tmp.replace(out_path)
    return out_path


def patch_start_sh_knobs(
    out_path: Path,
    knobs: dict[str, str],
    comment: str = "",
) -> None:
    """Patch existing start.sh assignment keys (optimize write-back)."""
    text = out_path.read_text(encoding="utf-8")
    for k, v in knobs.items():
        text = _replace_assignment(text, k, v)
    if comment:
        # insert note after shebang block
        lines = text.splitlines(True)
        insert_at = 1
        for i, line in enumerate(lines[:40]):
            if line.startswith("#"):
                insert_at = i + 1
            elif line.startswith("set "):
                break
        lines.insert(insert_at, f"# autotune: {comment}\n")
        text = "".join(lines)
    tmp = out_path.with_suffix(out_path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.chmod(tmp.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    tmp.replace(out_path)
